"use client";
import {useRef,useState} from 'react';
import {wallLength,wallPoint,wallPath,wallPart,nearestPathRatio,wallStats,validateWalls,suggestWalls,type Wall,type P} from './walls';
export type Guide={a:P;b:P;label:string;path?:P[]};
export function useWallEditor(width:number,height:number){
 const [walls,setWalls]=useState<Wall[]>([]),[locked,setLocked]=useState(false),[frozen,setFrozen]=useState(false),[selected,setSelected]=useState<number|null>(null),[message,setMessage]=useState(''),[guide,setGuide]=useState(0);
 const [mode,setMode]=useState<"select"|"guide"|"draw">("guide"),[draft,setDraft]=useState<P|null>(null),[hover,setHover]=useState<number|null>(null);
 const next=useRef(1);const current=walls.find(w=>w.id===selected);const stats=wallStats(walls);
 function commit(items:Wall[]){if(locked)return false;const error=validateWalls(items,width,height);if(error){setMessage(error);return false;}setWalls(items);setMessage('');return true;}
 function patch(w:Wall){return commit(walls.map(old=>old.id===w.id?w:old));}
 function move(id:number,delta:P){const w=walls.find(w=>w.id===id);if(!w||locked)return;if(frozen)return patch({...w,offset:delta});else return patch({...w,a:{x:w.a.x+delta.x,y:w.a.y+delta.y},b:{x:w.b.x+delta.x,y:w.b.y+delta.y},path:w.path?.map(p=>({x:p.x+delta.x,y:p.y+delta.y}))});}
 function add(g:Guide){if(frozen||locked)return;const w:Wall={id:next.current++,a:g.a,b:g.b,path:g.path,height:2.4,offset:{x:0,y:0},openings:[]};if(walls.some(x=>Math.hypot(x.a.x-w.a.x,x.a.y-w.a.y)<.01&&Math.hypot(x.b.x-w.b.x,x.b.y-w.b.y)<.01&&Math.abs(wallLength(x)-wallLength(w))<.01&&[.25,.5,.75].every(t=>{const a=wallPoint(x,wallLength(x)*t),b=wallPoint(w,wallLength(w)*t);return Math.hypot(a.x-b.x,a.y-b.y)<.01;}))){setMessage('這條牆已存在。');return;}if(commit([...walls,w])){setSelected(w.id);setMode("select");setDraft(null);}}
 const num=(label:string,value:number,change:(v:number)=>void,min=0,max=100,step=.1)=><label className="wall-number"><span>{label}</span><input aria-label={label} type="number" step={step} min={min} max={max} value={Math.round(value*100)/100} onChange={e=>{if(e.target.value!=='')change(Number(e.target.value));}}/></label>;
 function controls(guides:Guide[],trees:P[]){return <div className="wall-controls"><b>牆體・空間架構</b><p>點選底圖線條建牆；橘色為目前牆段。點牆編輯、拖牆移動。曲牆沿 STEP 02 弧線配置。</p><div className="tool-tabs">{([ ["select","選取／移動"],["guide","沿線建牆"],["draw","兩點畫牆"] ] as const).map(([id,label])=><button key={id} disabled={locked||(frozen&&id!=="select")} className={mode===id?"selected":""} onClick={()=>{setMode(id);setDraft(null);}}>{label}</button>)}</div><p>{mode==="guide"?"滑鼠移到直線或曲線會亮起，點一下即可建牆。":mode==="draw"?(draft?"點選終點完成直牆。":"在基地點選起點，再點終點。"):"點選牆身開啟編輯；拖曳牆身可移動整段。"}</p><label><input type="checkbox" checked={locked} onChange={e=>setLocked(e.target.checked)}/> {locked?'牆體圖層已鎖定':'鎖定牆體圖層'}</label><fieldset disabled={locked}>
 {!frozen&&<>{!walls.length&&<button className="primary" onClick={()=>{const suggested=suggestWalls(guides.filter(g=>!g.path),trees);if(commit(suggested)){next.current=suggested.length+1;setSelected(suggested[0]?.id??null);setMessage(suggested.length?'依分割方向建立少量主牆，避開樹冠並留出通行空間；可再拖曳修整。':'目前空間不足以產生建議，請手動加入短牆。');}}}>依底圖與植栽建議配置</button>}<details><summary>依名稱選線（含曲線）</summary><label>分割線／弧線／基地邊界<select value={guide} onChange={e=>{setGuide(Number(e.target.value));setHover(Number(e.target.value));setMode("guide");}}>{guides.map((g,i)=><option value={i} key={i}>{g.label}</option>)}</select></label><button className="secondary" disabled={!guides.length} onClick={()=>add(guides[guide%guides.length])}>＋ 加入依附牆</button><button className="secondary" onClick={()=>add({a:{x:width*.2,y:height*.5},b:{x:width*.7,y:height*.5},label:'自由牆'})}>＋ 自訂牆段</button></details><button className="primary" disabled={!walls.length} onClick={()=>{setFrozen(true);setMode("select");setDraft(null);setMessage('原始配置已固定；拆分牆段後可移動其中一段。');}}>固定原始配置，開始空間調整</button></>}
 <label>選取牆段<select value={selected??''} onChange={e=>{setSelected(Number(e.target.value));setMode("select");}}><option value="" disabled>尚未選取</option>{walls.map(w=><option key={w.id} value={w.id}>W{w.id}・{wallLength(w).toFixed(2)} m{Math.hypot(w.offset.x,w.offset.y)>.001?'・已移動':''}</option>)}</select></label>
 {current&&<>{num('牆高 m',current.height,v=>patch({...current,height:v}),.1,2.4)}{!frozen?<><p>拖曳牆身定位；拖曳端點調整牆長；曲牆端點沿原弧線滑動。以範圍控制截取想保留的直線或曲線。</p>{num("保留起點 %",(current.range?.[0]??0)*100,v=>patch({...current,range:[v/100,current.range?.[1]??1]}),0,99,1)}{num("保留終點 %",(current.range?.[1]??1)*100,v=>patch({...current,range:[current.range?.[0]??0,v/100]}),1,100,1)}{!current.path&&(['a','b'] as const).map((end)=><div key={end}>{num(`${end==='a'?'起':'終'}點 X m`,current[end].x,v=>patch({...current,[end]:{...current[end],x:v}}),0,width)}{num(`${end==='a'?'起':'終'}點 Y m`,current[end].y,v=>patch({...current,[end]:{...current[end],y:v}}),0,height)}</div>)}<button className="secondary" onClick={()=>{commit(walls.filter(w=>w.id!==current.id));setSelected(null);}}>刪除此牆</button></>:<><p>拖曳牆身平移；數值每次可微調 0.1 m。</p>{num('X 平移 m',current.offset.x,v=>move(current.id,{...current.offset,x:v}),-width,width)}{num('Y 平移 m',current.offset.y,v=>move(current.id,{...current.offset,y:v}),-height,height)}<button className="secondary" disabled={current.openings.length>0} onClick={()=>{const middle=wallLength(current)/2,id=next.current++;if(commit(walls.flatMap(w=>w.id===current.id?[wallPart(w,0,middle),{...wallPart(w,middle,wallLength(w)),id}]:[w])))setSelected(id);}}>等分此牆段</button><small>可重複等分；已有開口的牆段需先刪除開口。總長保持不變。</small><button className="secondary" onClick={()=>move(current.id,{x:0,y:0})}>還原此段位置</button>
 <details open><summary>牆面開口</summary><button className="secondary" onClick={()=>{const width=Math.min(1,wallLength(current));patch({...current,openings:[...current.openings,{id:next.current++,start:(wallLength(current)-width)/2,width,height:Math.min(2.1,current.height),sill:0}]});}}>＋ 開口（預設門洞）</button>{current.openings.map((o,i)=><div className="wall-opening" key={o.id}><b>開口 {i+1}・{(o.width*o.height).toFixed(2)} m²</b>{num('距牆起點 m',o.start,v=>patch({...current,openings:current.openings.map(p=>p.id===o.id?{...p,start:v}:p)}),0,wallLength(current))}{num('開口寬 m',o.width,v=>patch({...current,openings:current.openings.map(p=>p.id===o.id?{...p,width:v}:p)}),.1,wallLength(current))}{num('窗台高 m',o.sill,v=>patch({...current,openings:current.openings.map(p=>p.id===o.id?{...p,sill:v}:p)}),0,current.height)}{num('開口高 m',o.height,v=>patch({...current,openings:current.openings.map(p=>p.id===o.id?{...p,height:v}:p)}),.1,current.height)}<button onClick={()=>patch({...current,openings:current.openings.filter(p=>p.id!==o.id)})}>刪除開口</button></div>)}</details></>}</>}
 </fieldset><div className="validation pass"><b>{frozen?'原始總長':'配置總長'} {stats.total.toFixed(2)} m</b><span>移動 {stats.moved.toFixed(2)} / {(stats.total/4).toFixed(2)} m（上限 25%）<br/>開口 {stats.area.toFixed(2)} / 12 m²</span></div><p role="status">{message||'以必要的少量牆面與開口形成清楚的圍合、引導與留白。'}</p><button className="secondary" disabled={locked} onClick={()=>{setWalls([]);setFrozen(false);setSelected(null);setDraft(null);setMode("guide");setHover(null);setMessage('已清除牆體，可重新建立原始配置。');}}>清除牆體，重新配置</button></div>;}
 return {walls,locked,setLocked,frozen,selected,setSelected,move,controls,mode,setMode,draft,setDraft,hover,setHover,add,patch};
}
export function WallPlan({editor,x,y,scale,dimensions,editable,guides,width,height}:{editor:ReturnType<typeof useWallEditor>;x:number;y:number;scale:number;dimensions:boolean;editable:boolean;guides:Guide[];width:number;height:number}){
 const ref=useRef<SVGGElement>(null),drag=useRef<{id:number;origin:P;offset:P;base:P;pointer:number;end?:"a"|"b"}|null>(null);
 const local=(e:React.PointerEvent)=>{const matrix=ref.current?.getScreenCTM();return matrix?new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()):null;};
 return <g ref={ref} transform={`translate(${x} ${y}) scale(${scale})`} onClick={e=>{if(editable)e.stopPropagation();}} onPointerMove={e=>{if(!drag.current)return;e.stopPropagation();const p=local(e),w=editor.walls.find(w=>w.id===drag.current!.id);if(!p||!w)return;const d=drag.current;if(d.end){if(w.path){const ratio=nearestPathRatio(w.path,p),range=w.range??[0,1];editor.patch({...w,range:d.end==="a"?[Math.min(ratio,range[1]-.01),range[1]]:[range[0],Math.max(ratio,range[0]+.01)]});}else editor.patch({...w,a:wallPoint(w,0),b:wallPoint(w,wallLength(w)),[d.end]:{x:Math.max(0,Math.min(width,p.x)),y:Math.max(0,Math.min(height,p.y))},range:undefined});return;}editor.move(w.id,{x:Math.round((p.x-d.origin.x+d.offset.x)*10)/10+(editor.frozen?0:d.base.x-w.a.x),y:Math.round((p.y-d.origin.y+d.offset.y)*10)/10+(editor.frozen?0:d.base.y-w.a.y)});}} onPointerUp={e=>{if(drag.current){e.stopPropagation();drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId);}}} onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}}>
 {editable&&!editor.locked&&!editor.frozen&&editor.mode==="draw"&&<rect data-editor-overlay="true" width={width} height={height} fill="transparent" style={{cursor:'crosshair'}} onClick={e=>{e.stopPropagation();const matrix=ref.current?.getScreenCTM();if(!matrix)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());if(editor.draft)editor.add({a:editor.draft,b:{x:p.x,y:p.y},label:'自訂直牆'});else editor.setDraft({x:p.x,y:p.y});}}/>}
 {editable&&!editor.locked&&!editor.frozen&&editor.mode==="guide"&&guides.map((g,i)=><path key={i} data-editor-overlay="true" d={wallPath({id:0,...g,height:2.4,offset:{x:0,y:0},openings:[]})} fill="none" stroke={editor.hover===i?'#ec861b':'#187cbd'} strokeOpacity={editor.hover===i?.8:.22} strokeWidth={(editor.hover===i?12:9)/scale} style={{cursor:'pointer'}} onPointerEnter={()=>editor.setHover(i)} onPointerLeave={()=>editor.setHover(null)} onClick={e=>{e.stopPropagation();editor.add(g);}}><title>{g.label}：點選建牆</title></path>)}
 {editor.draft&&editable&&<circle data-editor-overlay="true" cx={editor.draft.x} cy={editor.draft.y} r={6/scale} fill="#ed7c15"/>}
 {editor.walls.map(w=>{const a=wallPoint(w,0),b=wallPoint(w,wallLength(w)),angle=Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;const at=(s:number)=>wallPoint(w,s);const cuts=w.openings.filter(o=>o.sill<=1.2&&o.sill+o.height>=1.2).sort((a,b)=>a.start-b.start);let previous=0;const ranges:number[][]=[];for(const o of cuts){ranges.push([previous,o.start]);previous=o.start+o.width;}ranges.push([previous,wallLength(w)]);return <g key={w.id}>
 {ranges.map(([s,t],i)=><path key={i} d={wallPath(w,s,t)} fill="none" stroke="#48423b" strokeWidth=".2"/>)}
 {cuts.map(o=><path key={o.id} d={wallPath(w,o.start,o.start+o.width)} fill="none" stroke="#48423b" strokeWidth=".04" strokeDasharray=".15 .15"/>)}
 {dimensions&&<g pointerEvents="none" transform={`translate(${at(wallLength(w)/2).x} ${at(wallLength(w)/2).y}) rotate(${angle>90||angle< -90?angle+180:angle})`}><text y="-.45" textAnchor="middle" fontSize={13/scale} fill="#302d29" stroke="white" strokeWidth={3/scale} paintOrder="stroke">W{w.id}・L {wallLength(w).toFixed(2)} / H {w.height.toFixed(1)} m</text></g>}
 {editable&&!editor.locked&&<path data-editor-overlay="true" d={wallPath(w)} fill="none" stroke={editor.selected===w.id?'#c77720':'transparent'} strokeOpacity=".5" strokeWidth={16/scale} style={{cursor:'grab'}} onPointerDown={e=>{e.stopPropagation();const p=local(e);if(!p)return;editor.setSelected(w.id);editor.setMode("select");editor.setDraft(null);drag.current={id:w.id,origin:p,base:w.a,offset:editor.frozen?w.offset:{x:0,y:0},pointer:e.pointerId};ref.current?.setPointerCapture(e.pointerId);}}/>}
 {editable&&!editor.locked&&!editor.frozen&&editor.selected===w.id&&(['a','b'] as const).map(end=><circle key={end} data-editor-overlay="true" cx={(end==="a"?a:b).x} cy={(end==="a"?a:b).y} r={7/scale} fill="white" stroke="#c77720" strokeWidth={2/scale} style={{cursor:'crosshair'}} onPointerDown={e=>{e.stopPropagation();const p=local(e);if(!p)return;drag.current={id:w.id,origin:p,base:w.a,offset:{x:0,y:0},pointer:e.pointerId,end};ref.current?.setPointerCapture(e.pointerId);}}/>)}
 </g>;})}</g>;
}
