"use client";
import {useRef,useState} from 'react';
import {boundaryWalls,boundaryNames,perforatedOpenings,findOpeningStart,wallMoved,relocateWall,wallLength,wallPoint,wallPath,wallPart,nearestPathRatio,wallStats,WALL_MOVE_FRACTION,WALL_OPENING_LIMIT,validateWalls,suggestWalls,wallExperience,type Wall,type P} from './walls';
export type Guide={a:P;b:P;label:string;path?:P[]};
function WallExperienceInfo({wall}:{wall:Wall}){const info=wallExperience(wall),id=`wall-experience-${wall.id}`;return <span className="wall-experience"><b>{info.kind}</b><button type="button" className="ratio-info" popoverTarget={id} aria-label={`${info.kind}的空間知覺與行為體驗`}>ⓘ</button><span id={id} popover="auto" className="ratio-popover"><header><b>{info.kind}｜空間知覺與行為體驗</b><button type="button" popoverTarget={id} popoverTargetAction="hide" aria-label="關閉說明">×</button></header><p>{info.description}</p><p>牆高 {wall.height.toFixed(1)} m；開口 {wall.openings.length} 處。平面、剖面與軸測圖皆依實際保留牆段及開口顯示。</p></span></span>}
export function useWallEditor(width:number,height:number){
 const [walls,setWalls]=useState<Wall[]>([]),[locked,setLocked]=useState(false),[frozen,setFrozen]=useState(false),[selected,setSelected]=useState<number|null>(null),[message,setMessage]=useState(''),[guide,setGuide]=useState(0);
 const [mode,setMode]=useState<"select"|"guide"|"draw"|"place">("guide"),[draft,setDraft]=useState<P|null>(null),[hover,setHover]=useState<number|null>(null);
 const [originalTotal,setOriginalTotal]=useState<number|null>(null),[rejected,setRejected]=useState('');
 const started=useRef(false);
 const [gapCount,setGapCount]=useState(4),[gapWidth,setGapWidth]=useState(.2);
 const next=useRef(1);const current=walls.find(w=>w.id===selected);const stats=wallStats(walls);
 const limit=(originalTotal??stats.total)*WALL_MOVE_FRACTION;
 const constraintsActive=frozen&&originalTotal!==null&&originalTotal>0;
 const currentError=validateWalls(walls,width,height,originalTotal??undefined);
 function commit(items:Wall[]){if(locked)return false;if(walls.some(w=>w.locked&&JSON.stringify(items.find(p=>p.id===w.id))!==JSON.stringify(w))){setRejected('請先解鎖要修改的牆段。');return false;}const error=validateWalls(items,width,height,originalTotal??undefined);if(error){setRejected(error);setMessage('');return false;}setWalls(items);setRejected('');setMessage('');return true;}
 function freeze(){if(locked){setRejected('請先解除牆體圖層鎖定，再啟用空間調整。');return;}if(!walls.length){setRejected('至少需要一段牆體，才能固定原始配置。');return;}const error=validateWalls(walls,width,height);if(error){setRejected(error);return;}const baseline=stats.total;setOriginalTotal(baseline);setFrozen(true);setMode('select');setDraft(null);setRejected('');const long=walls.filter(w=>wallLength(w)>baseline*WALL_MOVE_FRACTION+1e-7);setMessage(long.length?`限制已啟動。${long.map(w=>`W${w.id}`).join('、')} 單段長度超過 25% 額度，請先選取並按「等分此牆段」。`:'限制已啟動。請選取牆段後拖曳，或輸入 X／Y 平移量；超額修改會被拒絕並保留原配置。');}
 function check(){const error=validateWalls(walls,width,height,originalTotal??undefined);setRejected(error);setMessage(error?'':!walls.length?'尚未配置牆體。':!frozen?'初始配置尺寸與開口有效；請固定原始配置後再進行移動調整。':'檢核通過：總長保持不變、移動牆段不超過 25%、開口不超過 12 m²，牆高與基地範圍皆符合。');}

 function begin(){if(started.current||walls.length)return;started.current=true;const items=boundaryWalls(width,height,next.current);if(commit(items)){next.current+=4;setSelected(items[0].id);setMode('select');}}
 function boundary(index:number,present:boolean){if(frozen||locked)return;const existing=walls.find(w=>w.boundary===boundaryNames[index]);if(existing?.locked){setRejected('請先解鎖此邊界牆。');return;}if(present&&!existing){const w=boundaryWalls(width,height,next.current)[index];w.id=next.current++;if(commit([...walls,w]))setSelected(w.id);}else if(!present&&existing&&commit(walls.filter(w=>w.id!==existing.id)))setSelected(null);}
 function toggleLayer(id:number,key:'locked'|'hidden'){if(locked)return;setWalls(items=>items.map(w=>w.id===id?{...w,[key]:!w[key]}:w));setDraft(null);setMode('select');setRejected('');}
 function place(start:P,end:P){if(!frozen||!current||locked||current.locked||current.hidden)return;if(Math.hypot(end.x-start.x,end.y-start.y)<.1){setRejected('兩個定位點至少相距 0.1 m。');return;}if(patch(relocateWall(current,start,end))){setMode('select');setDraft(null);}}
 function addOpening(kind:'door'|'gap'|'window'){if(!current||current.locked||current.hidden)return;const w=Math.min(1,wallLength(current)),h=kind==='gap'?current.height:kind==='window'?Math.min(1,current.height):Math.min(2.1,current.height),sill=kind==='window'?Math.min(1,current.height-h):0;const start=findOpeningStart(current,w,h,sill);if(start===null){setRejected('此牆沒有足夠的不重疊位置，請先調整現有開口。');return;}patch({...current,openings:[...current.openings,{id:next.current++,start,width:w,height:h,sill}]});}
 function perforate(){if(!current||current.locked||current.hidden)return;const openings=perforatedOpenings(current,gapCount,gapWidth,next.current);if(patch({...current,openings})){next.current+=gapCount;}}
 function patch(w:Wall){return commit(walls.map(old=>old.id===w.id?w:old));}
 function move(id:number,delta:P){const w=walls.find(w=>w.id===id);if(!w||locked||w.locked||w.hidden)return;if(frozen){if(!constraintsActive){setRejected('限制尚未完成啟用，請返回初始配置後重新固定原始總長。');return false;}const returning=Math.hypot(delta.x,delta.y)<=.001;if(!returning&&!wallMoved(w)&&wallLength(w)>limit-stats.moved+1e-7){setRejected(`W${w.id} 長 ${wallLength(w).toFixed(2)} m，超過剩餘可移動牆長 ${(limit-stats.moved).toFixed(2)} m。請先按「等分此牆段」。`);setMessage('');return false;}return patch({...w,offset:delta});}return patch({...w,a:{x:w.a.x+delta.x,y:w.a.y+delta.y},b:{x:w.b.x+delta.x,y:w.b.y+delta.y},path:w.path?.map(p=>({x:p.x+delta.x,y:p.y+delta.y}))});}
 function add(g:Guide){if(frozen||locked)return;const w:Wall={id:next.current++,a:g.a,b:g.b,path:g.path,height:2.4,offset:{x:0,y:0},openings:[]};if(walls.some(x=>Math.hypot(x.a.x-w.a.x,x.a.y-w.a.y)<.01&&Math.hypot(x.b.x-w.b.x,x.b.y-w.b.y)<.01&&Math.abs(wallLength(x)-wallLength(w))<.01&&[.25,.5,.75].every(t=>{const a=wallPoint(x,wallLength(x)*t),b=wallPoint(w,wallLength(w)*t);return Math.hypot(a.x-b.x,a.y-b.y)<.01;}))){setMessage('這條牆已存在。');return;}if(commit([...walls,w])){setSelected(w.id);setMode("select");setDraft(null);}}
 const num=(label:string,value:number,change:(v:number)=>void,min=0,max=100,step=.1)=><label className="wall-number"><span>{label}</span><input aria-label={label} type="number" step={step} min={min} max={max} value={Math.round(value*100)/100} onChange={e=>{if(e.target.value!=='')change(Number(e.target.value));}}/></label>;
 function controls(guides:Guide[],trees:P[]){return <div className="wall-controls"><b>牆體・空間架構</b><p className="wall-workflow">① 邊界圍合 → ② 內部片牆 → ③ 固定配置 → ④ 移動／穿鑿</p>
 <details className="wall-design-notes"><summary>如何以少量牆體組織空間？</summary><p>先看基地長短向、平面分割、樹陣與行進方向。以少量片牆形成背靠、轉折與視線焦點；入口宜回應動線，錯位牆面可引導空間流。四面圍合只是起點，不是必須保留的結果。</p><p>simplicity, clarity：reduction to essential。每加一段牆或一個開口，都應說得出它的空間作用；12 m² 是上限，不是目標。</p></details>
 <section className={`wall-check validation ${rejected||currentError?'fail':constraintsActive?'pass':'pending'}`} aria-label="牆體規則檢核">
 <b>{constraintsActive?'● 空間調整｜限制已啟用（執行中）':'初始配置｜尚未固定基準'}</b>
 <span>配置總長 {stats.total.toFixed(2)} m{originalTotal!==null&&<>／原始 {originalTotal.toFixed(2)} m</>}</span>
 {constraintsActive?<><span>移動牆段 {stats.moved.toFixed(2)} / {limit.toFixed(2)} m（{originalTotal? (stats.moved/originalTotal*100).toFixed(1):'0.0'}%／上限 25%）<br/>剩餘可移動牆長 {Math.max(0,limit-stats.moved).toFixed(2)} m</span><progress aria-label="移動牆長額度" value={stats.moved} max={limit||1}/><span>開口總面積 {stats.area.toFixed(2)} / {WALL_OPENING_LIMIT} m²<br/>剩餘開口面積 {Math.max(0,WALL_OPENING_LIMIT-stats.area).toFixed(2)} m²</span><progress aria-label="開口面積額度" value={stats.area} max={WALL_OPENING_LIMIT}/></>:<span>配置總長尚無指定上限。固定後可移動 {(stats.total*.25).toFixed(2)} m；開口 {stats.area.toFixed(2)} / 12 m²（剩餘 {Math.max(0,12-stats.area).toFixed(2)} m²）。</span>}
 <small>{constraintsActive?'限制正在執行：移動額度按整段牆長計算，不是平移距離；超額操作會立即拒絕。重複移動同段只計一次，還原位置即釋出額度。曲牆按弧長計算，開口不扣減配置總長。':'此階段拖曳是初始定位，不計移動額度。開口面積從初始配置起即受限；完成建牆後固定原始總長，啟用移動限制。'}</small>
 {(rejected||currentError)&&<p role="alert" className="wall-rejection">{rejected?'本次修改未套用，保留上一次有效配置。':''}{rejected||currentError}</p>}
 <button type="button" className="secondary" onClick={check}>檢核目前配置</button><p role="status" aria-live="polite">{message}</p>
 </section>
 {!frozen&&<details open className="boundary-setup"><summary>① 邊界設定｜初始方案</summary><p>預設四面實牆，高 2.4 m。未設牆的邊界屬初始開放側，不算穿鑿；固定後不能藉刪牆改變原始總長。</p><div className="boundary-grid">{boundaryNames.map((name,i)=>{const w=walls.find(w=>w.boundary===name);return <div key={name}><label><input type="checkbox" checked={!!w} disabled={locked||w?.locked} onChange={e=>boundary(i,e.target.checked)}/>{name} {w?'實牆／開口':'未設牆'}</label>{w&&<button type="button" onClick={()=>{setSelected(w.id);setMode('select');setDraft(null);}}>編輯</button>}</div>;})}</div><small>勾選邊界後，可在下方「牆面／邊界開口」改為局部缺口或透空間隙。</small></details>}
 <p>點選底圖線條建牆；橘色為目前牆段。點牆編輯、拖牆移動。曲牆沿 STEP 02 弧線配置。</p><div className="tool-tabs">{([ ["select","選取／移動"],["guide","沿線建牆"],["draw","兩點畫牆"] ] as const).map(([id,label])=><button key={id} disabled={locked||(frozen&&id!=="select")} className={mode===id?"selected":""} onClick={()=>{setMode(id);setDraft(null);}}>{label}</button>)}</div><p>{mode==="guide"?"滑鼠移到直線或曲線會亮起，點一下即可建牆。":mode==="draw"?(draft?"點選終點完成直牆。":"在基地點選起點，再點終點。"):mode==="place"?(draft?"點第二點決定方向；牆長保持不變。":"在基地點選新的牆段起點，再點第二點決定方向。"):"點選牆身開啟編輯；拖曳牆身可移動整段。"}</p>{(mode==='draw'||mode==='place')&&<button type="button" className="secondary" onClick={()=>{setDraft(null);setMode('select');}}>取消兩點操作</button>}<label><input type="checkbox" checked={locked} onChange={e=>setLocked(e.target.checked)}/> {locked?'牆體圖層已鎖定':'鎖定牆體圖層'}</label><fieldset disabled={locked}>
 {!frozen&&<>{!walls.length&&<button className="primary" onClick={()=>{const suggested=suggestWalls(guides.filter(g=>!g.path),trees);if(commit(suggested)){next.current=suggested.length+1;setSelected(suggested[0]?.id??null);setMessage(suggested.length?'依分割方向建立少量主牆，避開樹冠並留出通行空間；可再拖曳修整。':'目前空間不足以產生建議，請手動加入短牆。');}}}>依底圖與植栽建議配置</button>}<details><summary>依名稱選線（含曲線）</summary><label>分割線／弧線／基地邊界<select value={guide} onChange={e=>{setGuide(Number(e.target.value));setHover(Number(e.target.value));setMode("guide");}}>{guides.map((g,i)=><option value={i} key={i}>{g.label}</option>)}</select></label><button className="secondary" disabled={!guides.length} onClick={()=>add(guides[guide%guides.length])}>＋ 加入依附牆</button><button className="secondary" onClick={()=>add({a:{x:width*.2,y:height*.5},b:{x:width*.7,y:height*.5},label:'自由牆'})}>＋ 自訂牆段</button></details><button className="primary" disabled={!walls.length} onClick={freeze}>固定原始配置，開始空間調整</button></>}
 <details className="wall-layer-list"><summary>牆體圖層｜{walls.length} 段</summary><p>隱藏只影響顯示與匯出，仍納入所有額度；鎖定後不能移動、開口或刪除。</p>{walls.map(w=><div className="wall-layer-row" key={w.id}><button type="button" onClick={()=>{setSelected(w.id);setMode('select');setDraft(null);}}>W{w.id} {w.boundary??(w.path?'曲牆':'內部牆')}</button><small>{wallExperience(w).kind}</small><label><input type="checkbox" checked={!w.hidden} onChange={()=>toggleLayer(w.id,'hidden')}/>顯示</label><label><input type="checkbox" checked={!!w.locked} onChange={()=>toggleLayer(w.id,'locked')}/>鎖定</label></div>)}</details>
 <label>選取牆段<select value={selected??''} onChange={e=>{setSelected(Number(e.target.value));setMode("select");}}><option value="" disabled>尚未選取</option>{walls.map(w=><option key={w.id} value={w.id}>W{w.id} {w.boundary??''}・{wallLength(w).toFixed(2)} m{wallMoved(w)?'・已移動':''}</option>)}</select></label>
 {current&&<div className="current-wall-experience"><span>W{current.id} 空間型態</span><WallExperienceInfo wall={current}/></div>}
 {current&&constraintsActive&&<div className={`wall-move-readiness ${wallMoved(current)||wallLength(current)<=limit-stats.moved+1e-7?'ready':'blocked'}`} role="status"><b>{wallMoved(current)?`W${current.id} 已列入移動額度`:wallLength(current)<=limit-stats.moved+1e-7?`W${current.id} 可移動`:`W${current.id} 暫不可移動`}</b><span>本段 {wallLength(current).toFixed(2)} m／剩餘額度 {Math.max(0,limit-stats.moved).toFixed(2)} m</span><small>{wallMoved(current)?'可繼續調整位置；還原至 X 0、Y 0 會釋出本段額度。':wallLength(current)<=limit-stats.moved+1e-7?'拖曳牆身，或使用下方 X／Y 平移欄位。':'本段大於剩餘額度，請先按「等分此牆段」再移動。'}</small></div>}
 {current&&<fieldset disabled={locked||current.locked||current.hidden}><legend>編輯 W{current.id} {current.locked?'（已鎖定）':current.hidden?'（已隱藏）':''}</legend>{num('牆高 m',current.height,v=>patch({...current,height:v}),.1,2.4)}{!frozen?<><p>拖曳牆身定位；拖曳端點調整牆長；曲牆端點沿原弧線滑動。以範圍控制截取想保留的直線或曲線。</p>{num("保留起點 %",(current.range?.[0]??0)*100,v=>patch({...current,range:[v/100,current.range?.[1]??1]}),0,99,1)}{num("保留終點 %",(current.range?.[1]??1)*100,v=>patch({...current,range:[current.range?.[0]??0,v/100]}),1,100,1)}{!current.path&&(['a','b'] as const).map((end)=><div key={end}>{num(`${end==='a'?'起':'終'}點 X m`,current[end].x,v=>patch({...current,[end]:{...current[end],x:v}}),0,width)}{num(`${end==='a'?'起':'終'}點 Y m`,current[end].y,v=>patch({...current,[end]:{...current[end],y:v}}),0,height)}</div>)}<button className="secondary" onClick={()=>{commit(walls.filter(w=>w.id!==current.id));setSelected(null);}}>刪除此牆</button></>:<><p>此段長 {wallLength(current).toFixed(2)} m。拖曳或輸入平移量皆即時檢核；超過剩餘牆長額度時，請先等分牆段。數值每次可微調 0.1 m。</p>{num('X 平移 m',current.offset.x,v=>move(current.id,{...current.offset,x:v}),-width,width)}{num('Y 平移 m',current.offset.y,v=>move(current.id,{...current.offset,y:v}),-height,height)}<button className="secondary" disabled={current.openings.length>0} onClick={()=>{const middle=wallLength(current)/2,id=next.current++;if(commit(walls.flatMap(w=>w.id===current.id?[wallPart(w,0,middle),{...wallPart(w,middle,wallLength(w)),id}]:[w])))setSelected(id);}}>等分此牆段</button><small>可重複等分；已有開口的牆段需先刪除開口。總長保持不變。</small><button className="secondary" onClick={()=>{patch({...current,offset:{x:0,y:0},rotation:0});}}>還原此段位置</button><button className="secondary" onClick={()=>{setMode('place');setDraft(null);}}>兩點重新定位（保留牆長）</button><small>第一點決定位置，第二點決定方向；整段牆長計入移動額度。</small>
 </>}<details open className="wall-apertures"><summary>牆面／邊界開口</summary><p>全高缺口與透空間隙按寬 × 牆高計入 12 m²；門窗按實際寬 × 高。透空為實際挖空，非透明材質。</p><div className="opening-actions"><button className="secondary" onClick={()=>addOpening('door')}>＋ 門洞</button><button className="secondary" onClick={()=>addOpening('gap')}>＋ 全高缺口</button><button className="secondary" onClick={()=>addOpening('window')}>＋ 景窗</button></div><details><summary>改為透空邊界</summary>{num('透空間隙數',gapCount,v=>setGapCount(Math.max(1,Math.min(30,Math.round(v)))),1,30,1)}{num('間隙寬 m',gapWidth,v=>setGapWidth(Math.max(.05,v)),.05,wallLength(current))}<p>預計 {gapCount*gapWidth*current.height < 1000?(gapCount*gapWidth*current.height).toFixed(2):'超額'} m²（取代此段既有開口）。</p><button className="secondary" onClick={perforate}>套用等距透空間隙</button></details>{current.openings.length>0&&<button className="secondary" onClick={()=>patch({...current,openings:[]})}>改為實牆（移除本段開口）</button>}{current.openings.map((o,i)=><div className="wall-opening" key={o.id}><b>開口 {i+1}・{(o.width*o.height).toFixed(2)} m²</b>{num('距牆起點 m',o.start,v=>patch({...current,openings:current.openings.map(p=>p.id===o.id?{...p,start:v}:p)}),0,wallLength(current))}{num('開口寬 m',o.width,v=>patch({...current,openings:current.openings.map(p=>p.id===o.id?{...p,width:v}:p)}),.1,wallLength(current))}{num('窗台高 m',o.sill,v=>patch({...current,openings:current.openings.map(p=>p.id===o.id?{...p,sill:v}:p)}),0,current.height)}{num('開口高 m',o.height,v=>patch({...current,openings:current.openings.map(p=>p.id===o.id?{...p,height:v}:p)}),.1,current.height)}<button onClick={()=>patch({...current,openings:current.openings.filter(p=>p.id!==o.id)})}>刪除開口</button></div>)}</details></fieldset>}
 </fieldset><button className="secondary" disabled={locked||walls.some(w=>w.locked)} onClick={()=>{started.current=true;setWalls([]);setFrozen(false);setOriginalTotal(null);setRejected('');setSelected(null);setDraft(null);setMode("guide");setHover(null);setMessage('已清除牆體，可重新建立原始配置。');}}>清除牆體，重新配置</button></div>;}
 return {begin,boundary,place,walls,locked,setLocked,frozen,selected,setSelected,move,controls,mode,setMode,draft,setDraft,hover,setHover,add,patch};
}
export function WallPlan({editor,x,y,scale,dimensions,editable,guides,width,height}:{editor:ReturnType<typeof useWallEditor>;x:number;y:number;scale:number;dimensions:boolean;editable:boolean;guides:Guide[];width:number;height:number}){
 const ref=useRef<SVGGElement>(null),drag=useRef<{id:number;origin:P;offset:P;base:P;pointer:number;end?:"a"|"b"}|null>(null);
 const local=(e:React.PointerEvent)=>{const matrix=ref.current?.getScreenCTM();return matrix?new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse()):null;};
 return <g ref={ref} transform={`translate(${x} ${y}) scale(${scale})`} onClick={e=>{if(editable)e.stopPropagation();}} onPointerMove={e=>{if(!drag.current)return;e.stopPropagation();const p=local(e),w=editor.walls.find(w=>w.id===drag.current!.id);if(!p||!w||editor.locked||w.locked||w.hidden)return;const d=drag.current;if(d.end){if(w.path){const ratio=nearestPathRatio(w.path,p),range=w.range??[0,1];editor.patch({...w,range:d.end==="a"?[Math.min(ratio,range[1]-.01),range[1]]:[range[0],Math.max(ratio,range[0]+.01)]});}else editor.patch({...w,a:wallPoint(w,0),b:wallPoint(w,wallLength(w)),[d.end]:{x:Math.max(0,Math.min(width,p.x)),y:Math.max(0,Math.min(height,p.y))},range:undefined});return;}editor.move(w.id,{x:Math.round((p.x-d.origin.x+d.offset.x)*10)/10+(editor.frozen?0:d.base.x-w.a.x),y:Math.round((p.y-d.origin.y+d.offset.y)*10)/10+(editor.frozen?0:d.base.y-w.a.y)});}} onPointerUp={e=>{if(drag.current){e.stopPropagation();drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId);}}} onPointerCancel={()=>{drag.current=null;}} onLostPointerCapture={()=>{drag.current=null;}}>
 {editable&&!editor.locked&&(editor.mode==="draw"||editor.mode==="place")&&<rect data-editor-overlay="true" width={width} height={height} fill="transparent" style={{cursor:'crosshair'}} onClick={e=>{e.stopPropagation();const matrix=ref.current?.getScreenCTM();if(!matrix)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());if(editor.draft){if(editor.mode==='place')editor.place(editor.draft,{x:p.x,y:p.y});else editor.add({a:editor.draft,b:{x:p.x,y:p.y},label:'自訂直牆'});}else editor.setDraft({x:p.x,y:p.y});}}/>}
 {editable&&!editor.locked&&!editor.frozen&&editor.mode==="guide"&&guides.map((g,i)=><path key={i} data-editor-overlay="true" d={wallPath({id:0,...g,height:2.4,offset:{x:0,y:0},openings:[]})} fill="none" stroke={editor.hover===i?'#ec861b':'#187cbd'} strokeOpacity={editor.hover===i?.8:.22} strokeWidth={(editor.hover===i?12:9)/scale} style={{cursor:'pointer'}} onPointerEnter={()=>editor.setHover(i)} onPointerLeave={()=>editor.setHover(null)} onClick={e=>{e.stopPropagation();editor.add(g);}}><title>{g.label}：點選建牆</title></path>)}
 {editor.draft&&editable&&<circle data-editor-overlay="true" cx={editor.draft.x} cy={editor.draft.y} r={6/scale} fill="#ed7c15"/>}
 {editor.walls.filter(w=>!w.hidden).map(w=>{const a=wallPoint(w,0),b=wallPoint(w,wallLength(w)),angle=Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;const at=(s:number)=>wallPoint(w,s);const cuts=w.openings.filter(o=>o.sill<=1.2&&o.sill+o.height>=1.2).sort((a,b)=>a.start-b.start);let previous=0;const ranges:number[][]=[];for(const o of cuts){ranges.push([previous,o.start]);previous=o.start+o.width;}ranges.push([previous,wallLength(w)]);return <g key={w.id} pointerEvents={editor.mode==='draw'||editor.mode==='place'?'none':undefined}>
 {ranges.map(([s,t],i)=><path key={i} d={wallPath(w,s,t)} fill="none" stroke="#48423b" strokeWidth=".2"/>)}
 {cuts.map(o=><path key={o.id} d={wallPath(w,o.start,o.start+o.width)} fill="none" stroke="#48423b" strokeWidth=".04" strokeDasharray=".15 .15"/>)}
 {dimensions&&<g pointerEvents="none" transform={`translate(${at(wallLength(w)/2).x} ${at(wallLength(w)/2).y}) rotate(${angle>90||angle< -90?angle+180:angle})`}><text y="-.45" textAnchor="middle" fontSize={13/scale} fill="#302d29" stroke="white" strokeWidth={3/scale} paintOrder="stroke">W{w.id}・L {wallLength(w).toFixed(2)} / H {w.height.toFixed(1)} m</text></g>}
 {editable&&!editor.locked&&!w.locked&&editor.mode!=="draw"&&editor.mode!=="place"&&<path data-editor-overlay="true" d={wallPath(w)} fill="none" stroke={editor.selected===w.id?'#c77720':'transparent'} strokeOpacity=".5" strokeWidth={16/scale} style={{cursor:'grab'}} onPointerDown={e=>{e.stopPropagation();const p=local(e);if(!p)return;editor.setSelected(w.id);editor.setMode("select");editor.setDraft(null);drag.current={id:w.id,origin:p,base:w.a,offset:editor.frozen?w.offset:{x:0,y:0},pointer:e.pointerId};ref.current?.setPointerCapture(e.pointerId);}}/>}
 {editable&&!editor.locked&&!w.locked&&!editor.frozen&&editor.mode!=="draw"&&editor.selected===w.id&&(['a','b'] as const).map(end=><circle key={end} data-editor-overlay="true" cx={(end==="a"?a:b).x} cy={(end==="a"?a:b).y} r={7/scale} fill="white" stroke="#c77720" strokeWidth={2/scale} style={{cursor:'crosshair'}} onPointerDown={e=>{e.stopPropagation();const p=local(e);if(!p)return;drag.current={id:w.id,origin:p,base:w.a,offset:{x:0,y:0},pointer:e.pointerId,end};ref.current?.setPointerCapture(e.pointerId);}}/>)}
 </g>;})}</g>;
}
